In [10]:
import requests
import json
import pandas as pd

from datetime import datetime

In [28]:
def get_quotes_from_wsj(endpoint):
    headers = {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    quotes = requests.get(endpoint, headers=headers)
    df = pd.DataFrame(quotes.json()["data"]["instruments"])
    df = df[
        [
            "maturityDate",
            "coupon",
            "bid",
            "ask",
            "change",
            "askYield",
        ]
    ]

    timestamp = quotes.json()["data"]["timestamp"]
    timestamp_dt = datetime.strptime(timestamp, "%A, %B %d, %Y")
    # timestamp_str = datetime.strftime(timestamp_dt, "%Y%m%d")

    return (df, timestamp_dt)

In [29]:
endpoints = [
    "https://www.wsj.com/market-data/bonds/treasuries?id=%7B%22treasury%22%3A%22NOTES_AND_BONDS%22%7D&type=mdc_treasury",
    "https://www.wsj.com/market-data/bonds/treasuries?id=%7B%22treasury%22%3A%22BILLS%22%7D&type=mdc_treasury",
]

treasuries = get_quotes_from_wsj(endpoint=endpoints[0])
print(treasuries[1])
treasuries[0]

2024-07-23 00:00:00

    maturityDate coupon       bid       ask  change askYield
0      7/31/2024  1.750   99.2920   99.3020  0.0020   4.6080
1      7/31/2024  2.125   99.2940   99.3040  0.0040    4.568
2      7/31/2024  3.000   99.3000   99.3100  0.0060    4.611
3      8/15/2024  0.375   99.2200   99.2300  0.0060    5.090
4      8/15/2024  2.375   99.2560   99.2660   unch.    5.101
..           ...    ...       ...       ...     ...      ...
336    5/15/2053  3.625   86.0060   86.0260  0.6960    4.490
337    8/15/2053  4.125   94.0460   94.0660  0.0300    4.483
338   11/15/2053  4.750  104.1560  104.1760  0.0320    4.469
339    2/15/2054  4.250   96.0930   96.1130  0.0280    4.473
340    5/15/2054  4.625  102.1540  102.1740  0.0380    4.469

[341 rows x 6 columns]